export const APP = {
  'INIT': 'APP_INIT'
}

export const LOCALE = {
  'LOADING': 'LOCALE_LOADING',
  'LOADED': 'LOCALE_LOADED',
  'ERROR': 'LOCALE_ERROR'
}

export const PRODUCT_LIST = {
  'LOADING': 'PRODUCT_LIST_LOADING',
  'LOADED': 'PRODUCT_LIST_LOADED',
  'ERROR': 'PRODUCT_LIST_ERROR'
}

export const CART = {
  'CHANGE_QUANTITY': 'CART_CHANGE_QUANTITY',
  'CHECKOUT': 'CART_CHECKOUT',
  'CLEAR': 'CART_CLEAR'
}
